name: Build And Test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  Build and Test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Setup project
      run: yarn setup
    - name: Build Project
      run: yarn build
    - name: Run linter
      run: yarn lint
    - name: Test Project
      run: yarn test